# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-28 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hotelcal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=10)),
                ('date', models.IntegerField(max_length=2)),
                ('single', models.IntegerField(max_length=1)),
                ('double', models.IntegerField(max_length=1)),
                ('price', models.FloatField()),
                ('day', models.CharField(max_length=10)),
            ],
        ),
    ]
