# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-28 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelcal',
            old_name='price',
            new_name='double_price',
        ),
        migrations.AddField(
            model_name='hotelcal',
            name='single_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
