# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-28 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_auto_20180428_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelcal',
            name='date',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hotelcal',
            name='double',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hotelcal',
            name='single',
            field=models.IntegerField(),
        ),
    ]
